### ISSUE TITLE
`pip install pip --upgrade` breaks pip

### ISSUE THREAD

**Issue by andry81** [NulAsh/cpython#30]
* `Windows 7 x64`
* `python-3.10.1-win7-amd64-202112121259.exe`

```cmd
C:\Python\x64\310\Scripts>pip install pip --upgrade
Requirement already satisfied: pip in c:\python\x64\310\lib\site-packages (21.2.4)
Collecting pip
  Using cached pip-22.2-py3-none-any.whl (2.0 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
ERROR: Could not install packages due to an OSError: [WinError 5] Отказано в доступе: 'c:\\python\\x64\\310\\scripts\\pip.exe'
Consider using the `--user` option or check the permissions.


C:\Python\x64\310\Scripts>pip install pip --upgrade
Traceback (most recent call last):
  File "C:\Python\x64\310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\x64\310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\x64\310\Scripts\pip.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'
```

**Comment by andry81** [comment]
I've tried to test the original installer from `python.org` on the `Windows 8.1` and seems it has the issue. Upgrade to `3.10.5` does not fix it.
